version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.0
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - ./tmp/elasticsearch:/usr/share/elasticsearch/data
    
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/expenses_tracker_app
    ports:
      - "3000:3000"
    depends_on:
      - db
      - elasticsearch
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - ELASTICSEARCH_HOST=elasticsearch